baseURL = 'https://limewolf.top'
languageCode = "zh-cn"
title = 'è±å§†ç‹¼ğŸºçš„å°çª'
theme = 'hugo-theme-monochrome'
defaultContentLanguage = "zh-cn"
enableEmoji = true
paginate = 5
enableGitInfo = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]
