[zh-cn]
contentDir = "content/zh-cn"
languageName = "ç®€ä¸­"
languageCode = "zh-cn"
title = "è±å§†ç‹¼ğŸºçš„å°çª"
weight = 1
    [zh-cn.params]
        navbar_title = 'æ¬¢è¿æ¥åˆ°ç‹¼ğŸºçª(Den)'


[en]
contentDir = "content/en"
languageName = "English"
languageCode = "en"
title = "LimewolfğŸº's Den"
weight = 2
    [en.params]
        navbar_title = "Welcome to LimewolfğŸº's Den"