[zh-cn]
contentDir = "content/zh-cn"
languageName = "ç®€ä¸­"
languageCode = "zh-cn"
title = "è±å§†ç‹¼ğŸºçš„å°çª"
navbar_title = 'æ¬¢è¿æ¥åˆ°ç‹¼ğŸºçª(Den)'
weight = 1

[en]
contentDir = "content/en"
languageName = "English"
languageCode = "en"
title = "LimewolfğŸº's Den"
navbar_title = "Welcome to LimewolfğŸº's Den"
weight = 2